module.exports = {
  User: require("./user.model"),
  ShopSettings: require("./shopSettings.model"),
  Customer: require("./customer.model"),
  CustomerLedger: require("./customerLedger.model"),
  Supplier: require("./supplier.model"),
  SupplierLedger: require("./supplierLedger.model"),
  Category: require("./category.model"),
  Product: require("./product.model"),
  Sale: require("./sale.model"),
  SaleItem: require("./saleItem.model"),
  Purchase: require("./purchase.model"),
  PurchaseItem: require("./purchaseItem.model"),
  ExpenseCategory: require("./expenseCategory.model"),
  Expense: require("./expense.model"),
  CashBook: require("./cashBook.model"),
  BankAccount: require("./bankAccount.model"),
  BankTransaction: require("./bankTransaction.model"),
  DailyBook: require("./dailyBook.model"),
  Counter: require("./counter.model"),
};
